### ISSUE TITLE
Sky Factory 4 bug? ..... Project-E

### ISSUE THREAD

**Issue by ouzo2000** [Darkosto/SkyFactory4Issues#1003]
I can not see any crafting recipes from the project-e items. Both in gamemode 1 and tomanyitems.
But I can cheat the items and place this and they are working....
need Help?????

**Comment by sk2048** [comment]
ProjectE is currently disabled due to an issue that was unresolved at the time of the pack launch where EMC could not be generated for an item if said item had a staged recipe.

This has since been resolved, and it is currently undergoing testing. Should no further issues be found, ProjectE will be enabled in the next release of the pack.
