### ISSUE TITLE
I've experienced severe issues when changing the language.

### ISSUE THREAD

**Issue by ranan153** [Darkosto/SkyFactory4Issues#1029]
## Bug Report

When attempting to change the language, the game became unresponsive, almost crashed, and it took several minutes to change the language. It happened again, but worse when I went to change the language back. I experienced this issue changing the language to Russian (I think, I accidentally changed it to one of the Cyrillic languages at the top of the list,) and back to English (New Zealand.) 

## Expected Behaviour

I expected the language to change when I accidentally changed it, but my computer, which isn't a low powered build, almost wasn't able to handle what was happening.

## Possible Solution

I would imagine that the game uses a translator to go from the default language to a new one, rather than using pre-generated language packs, so it was most likely the translator that caused the issue. I don't know how that system works, so I couldn't give a fix, but I'd suggest looking there, if that is the case.

## Steps to Reproduce (for bugs)

1. Open language settings in the pause menu
2. Try to change the language
3. Pray the cpu doesn't melt

## Logs

* Client/Server Log: https://gist.github.com/ranan153/0372335d8c1a482ec41b1da4cd01257d
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in: 4.0.5

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sk2048** [comment]
Minecraft does use language files for translations. The problem is that changing the language triggers a reload of all resources and not just the language files. This is fine in vanilla, but in modded it's a huge undertaking to reload all the textures, models, sounds and language files.

It's the same process as happens when you change texture pack, and comes with the same issues. You shouldn't keep playing in the same session when changing texture/language. You should make the change, stop the game and reload so that Forge can do everything in the correct order.

**Comment by ranan153** [comment]
I can see that would be a large undertaking, and I incorrectly assumed how the translation worked. My apologies for taking up your time.
