### ISSUE TITLE
parabox only makes points in single loop runs

### ISSUE THREAD

**Issue by Grynder01** [Darkosto/SkyFactory4Issues#1043]
## Bug Report
I am having an issue where i leave the parabox running for like 4 hours while i sleep
the parabox starts the first loop and is maxed out on power i am using 5 of the 500m batteries from integrated dynamics full when i come back the stop loop button is greyed out and i can only do the deactivate option and it has generated no points

## Expected Behavior
I am looking for this to generate prestige points

## Possible Solution
run 1 loop at a time cause it always works like that

## Steps to Reproduce (for bugs)
1.start parabox with 2.5 billion rf in batteries and 8 petrified generators burning coal blocks fed from a filing cabinet with 40,000 blocks of supply
2.let idle for 4 hours and come back to no power lots of burned fuel and no prestige points

## World Information
Which Topography world are you using?
Preset: standard start
Do you have Prestige enabled? 
Prestige: yes
Please provide the version of the modpack that the world was created in if known. Rough estimates are OK
Modpack Version world created in: 4.0.5
If there are any additional mods, please state them below
Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.5
* Java Version:
* Launcher Used:t twitch
* Memory Allocated: 14 gigs
* Server/LAN/Single Player: sp
* Optifine Installed: no
* Shaders Enabled: no

**Comment by JackRuby1** [comment]
Are you inputting the power from your batteries into the parabox?

**Comment by Grynder01** [comment]
Yes I am 
I have 5 batteries of 500m rf directly touching it and set to output
That is enough to cap the machines power input in the first 10 minute cycle which is
2,147,483,647 and the machine uses 10,000,000 per cycle so thats enough for 214 cycles
I ran it again while I slept last night
When i checked this morning it was off and no points generated 
So i looked in the chat at the messages relating to the generation of points and it said that i ran out of power at 25 cycles and it gives the needed power for the next cycle that i did not meet.
The chat has no commas in the number so i really couldn't tell what the number was...I was sleepy and late for work and so in a hurry
I guess im goin to have to wait it out while im at the pc so i can actually see what is happening

**Comment by Crackerhead22** [comment]
There is an increase of 10million rf per point.

**Comment by Grynder01** [comment]
Really? I could have sworn it was a strait 10m per point i thought i put in just 20m the very first time and got 2 points 
I did that as a test to see if the rf cost was compounded per point and i thought it wasnt...i guess i need to look at it better

**Comment by Grynder01** [comment]
Im not at home right now but im pretty sure this cant be right because generating 25 points would cost 3,140,000,000 which is more than the power cap of the machine and i know acording to the chat messages i can generate 25 and it fails on 26

**Comment by FireJadian** [comment]
My quick math shows generating 25 points costing 3,250,000,000 RF, small difference but probably worth noting.

This is more than total power that the machine can hold at one time because it's consumed piece by piece, not in one chunk.  10 minutes in, it eats 10m RF.  10 minutes later, 20 minutes into the loop, it eats 20m RF.  After it consumes the RF, your batteries refill it.

After 220 minutes, the Parabox has eaten about 2.5 billion RF, the total capacity of your batteries.  All the RF used after this was produced by your Petrified Fuel Generators since 10 minutes in (or sooner, if your Parabox was empty at the start), with some time potentially being lost if the batteries fill up again.

The total RF consumption at 260 minutes, is 3.51 billion RF.

8 generators at 800 RF per tick is worth 6400 RF per tick, for 76.8 million RF per 10 minutes.  The RF stored by your batteries, plus the RF you generate during this 260 minute period, is 4.49 billion RF, assuming they run the whole time and aren't feeding other machines (like packagers to automate turning coal acorns/resin/pieces into coal into coal blocks).  So, I'm assuming that this setup wasn't just powering the Parabox but also the other machines in your base, putting on some extra drain.

In any case, after 250 minutes, the Parabox consumed the majority of RF you had stored and produced.  Your setup failed to supply the Parabox with another 260 million RF 10 minutes later, and so it deactivated.

If you want to idle your Parabox for longer than 4 hours, you'll probably want to step up your RF production.

**Comment by Grynder01** [comment]
Okay well this is a damn in-depth explanation and I appreciate it the Petrified fuel generators are actually only powering the parabox but one of the batteries did not start at full power so that's why you feel like there might have been an extra bleed on the system but I will definitely step up my power production thank you sir

**Comment by Grynder01** [comment]
Your math is correct on generating 25 points by the way I don't know how I came up with my number I missed something somewhere I'm sure
And also I put the full amount that the parabox box can hold and there was still reserves left in the battery so when it ate the first 10 or 20 million it immediately refilled the parabox to its limit and I didn't even notice that it ate the power

**Comment by Grynder01** [comment]
I am closing this issue because I have been schooled on how the parabox works
My assumptions and calculations were wrong and thus there was never a problem with the pack there was a problem with my understanding of how the features of the pack work
I would like to thank the people that helped me understand my flaws as this is the only way to improve ones self
Improvise adapt overcome
