### ISSUE TITLE
[Question] Cottonwood Amber recipe inconsistent with all other amber recipes

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#135]
The crafting table recipe for Cottonwood Amber has the ingredients reversed compared with other amber recipes. Is this intended? I imagine you will get a lot of reports because players will assume the same pattern.

![2019-03-16_15 00 31](https://user-images.githubusercontent.com/29290246/54480246-7f9f7c80-47fc-11e9-8c30-a50f49748d90.png)

![2019-03-16_15 00 57](https://user-images.githubusercontent.com/29290246/54480248-83cb9a00-47fc-11e9-98c8-5165fa941b05.png)

SkyFactory4-0.2.8

**Comment by Darkosto** [comment]
This one was an alternative recipe because it does not lead directly into a resource like Gold, Coal, or other ambers. It was purposely done to be consistent with some of the ambers are decorative or require processing later on.

I did, however, edit it a bit to help players out with knowing how things work a little better.
