### ISSUE TITLE
Armor/tinker tool advancement modifiers not triggering.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#199]
I embossed a paper chest piece onto a full cobble chestplate and the advancement part wasn't ticked off.
https://gyazo.com/c3fa6d89287a437ce1bd3295f3f874bd
https://gyazo.com/f40db0318775540b274b7f4781619a73

**Comment by JackRuby1** [comment]
The tinker tool one isn't triggering either.

**Comment by JackRuby1** [comment]
for the tool one, fortified isn't triggering either

**Comment by Mitchninja88** [comment]
This has happened for me as well. I added the modifies using the tool forge.

**Comment by Crackerhead22** [comment]
Okay, after looking at this I can see a couple of things.  Fortified and Polished are not in the list, and the way Embossment has changed the way it looks in NBT (technically so has Fortified and Polished).   Instead of `extratrait_armor` being the NBT tag, for exmaple; if I were to Emboss either an armor or tool with Paper, it would now look like `identifier:"extratraitpaperwritable1"' or 'identifier:"extratraitpaperwritable2_armor"` (with the number 1 or 2 after writable depending on part used to Emboss. With _armor being the one used on armor).

While Fortified would have `identifier:"fortifyMATERIAL` for tool/weapon.  Polished would be `identifier:"polished_armorMATERIAL` for armors.

**Comment by Crackerhead22** [comment]
Would suggest just removing tge Embossment part of the advancement.  @justinrusso ?
