### ISSUE TITLE
No background on main menu with Linux and MultiMC

### ISSUE THREAD

**Issue by Novasae** [Darkosto/SkyFactory4Issues#211]
Ubuntu 18.04 LTS

https://gist.github.com/Novasae/e746ec02fb76e89fc013f2cf1d86e61c

Just a pink/black missing texture, couldn't upload screenshot.

**Comment by ParkerMc** [comment]
Also missing background on the main menu on Arch Linux here is more of the bug info

## Bug Report
Background of the main menu is the missing texture.
https://i.imgur.com/zi8iCyq.png

## Expected Behaviour
Should show the background image

## Possible Solution
Have the assets mod used support unix like file systems. Probably just change "\" to "/". Forward slash should work on all oses. Will do some testing.

## Steps to Reproduce (for bugs)
1. Load up pack

## Logs
* Client/Server Log: https://gist.github.com/ParkerMc/262ee96b62bb9629ab48ddf1b8c8c5d6

## Client Information
* Modpack Version: 4.0.0
* Java Version: jdk 8
* Launcher Used: multi mc
* Memory Allocated: 3GB
* Optifine Installed: No
* Shaders Enabled: No

**Comment by ParkerMc** [comment]
After more testing, I have determined that `resources/test/textures/gui/title/background/BG_FULL.png`(and probably other files too for other things) have to be renamed to be case sensitive. For the background, this is `bg_full.png`. This fixed worked for me.

**Comment by sk2048** [comment]
That would do it, capitalisation matters on Linux.
