### ISSUE TITLE
Tinkers construct drying rack progress doesn't keep going while in advancement menu

### ISSUE THREAD

**Issue by freopt** [Darkosto/SkyFactory4Issues#224]
## Bug Report
The drying rack progress is stalled while in the advancement menu. This only happens while in the advancement menu (from what I can tell) and not when in your inventory or a gui

## Expected Behaviour
For the drying rack to continue progressing

## Steps to Reproduce (for bugs)
Put something on a drying rack and go into the advancement menu and watch it not work

here is video of problem:
https://imgur.com/a/d8cqdck

**Comment by sk2048** [comment]
Single player Minecraft pauses when the Advancements GUI is open. Everything is stalled while you have that GUI open.

The other GUIs you mention allow you to interact with the world, things keep on happening because you can change things from these GUIs. Throw an item on the ground, hopper things somewhere, put armour on...

This is not the case for advancements. You are not interacting with the world, so Minecraft pauses the world.

**Comment by freopt** [comment]
I see. Thanks
