### ISSUE TITLE
Together Forever vs Twilight Forest command conflict

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Darkosto/SkyFactory4Issues#244]
## Bug Report

./tf [info/invite] etc, brings up "You are not in the twilight forest dimension"
/togetherforever:tf info brings up correct info.
## Expected Behaviour

/tf brings up all the twilight forest commands.
/tf needs to be re-assigned to togetherforever
## Possible Solution

Reassign commands, or remove the shortcut from Twilight Forest

## Steps to Reproduce (for bugs)

1. Run /tf in game. A reply is given with the message "/tffeature <info|reactive|conquer|center>
2. Run /togetherforever:tf - correct information appears however a user now has to use the long version of the command.

## Logs

* Client/Server Log: Don't see why a log is necessary, all it shows is that I ran the command /tf
* Crash Log: N/A

## World Information

* Preset: Sky Factory 4

* Prestige: no

* Modpack Version world created in: 4.0.1

* Additional Content Installed: Spongeforge (that probably sums it up - Don't know how it messes with Twilight Forest though)

## Client Information

* Modpack Version: 4.0.1
* Java Version: Version 8 update 201
* Launcher Used: Twitch
* Memory Allocated: 4g Server 8g game
* Server/LAN/Single Player: Server 
* Optifine Installed: No
* Shaders Enabled: No

## Server Information 
* Java Version: Version 8 update 201
* Operating System: Windows server 2008 R2 Enterprise Service pack 1
* Hoster: Me
* Sponge (Non-Vanilla Forge) Server: Yes

**Comment by sk2048** [comment]
Unfortunately I don't believe we can stop Twilight Forest registering a perfectly valid alias for their command.

Together Forever does register other aliases, `/together` should work for example. I suggest you use this instead.

However, throughout testing, the Twilight Forest has never overridden the Together Forever alias. There are also no reports of this happening to people playing SevTech, which also uses both mods. I wonder if this is happening for you due to a change Sponge makes to command handling.

**Comment by nzminecraftDOTcom** [comment]
Ah wonderful. /together works. I will let my players know they should use that instead. Thank you!

**Comment by mtimyself** [comment]
The alternative command should be reflected in the Useful MP guide thing.
