### ISSUE TITLE
Advancement Book Broken | Sky Factory 4

### ISSUE THREAD

**Issue by d4julian** [Darkosto/SkyFactory4Issues#291]
## Context

Advancement book fixed please :)

* Link:
![Image](https://i.gyazo.com/37284836a6937069e139a16ea8c1faff.png)

## Mod Details
* Name: Sky Factory 4
* [CurseForge Link](https://minecraft.curseforge.com/projects/skyfactory-4)

**Comment by AshZification** [comment]
Did you turn it off and on again? (Specifically, did you close MC & restart, then if it persists, have you tried redownloading)

**Comment by d4julian** [comment]
This is a server. I even tried deleting the `world/advancements` folder and it worked for a bit, but in a few hours it broke again.

**Comment by ApolloMCC** [comment]
There is a fix for it.

**Comment by Menphis88** [comment]
> There is a fix for it.

Which would be what?????

**Comment by Yorkforce** [comment]
Just to update with extra info

On the server there is an advancementsbook.dat file in the world/data folder, when this issue occurs that file somehow gets deleted

**Comment by ParkerMc** [comment]
As a few people have asked me about this. The issue is not with the Advancement book mod(my mod). I assume the issue is with vanilla syncing the advancements. But I am happy to include a config option in my mod to make sure they sync.
Before that though. This may be related to https://bugs.mojang.com/browse/MC-118389.

**Comment by ParkerMc** [comment]
(didn't mean to press comment yet)
Before that though. This may be related to [MC-118389](https://bugs.mojang.com/browse/MC-118389). If someone who is having this issue would try `/advancement revoke <their username> only sf4:age1/root` then `/advancement grant <username> only sf4:age1/root` while they are on the server that will tell us if it is related to that(this has the potential to remove all advancements so keep a backup handy and don't blame me). If that doesn't fix it throw up a simple issue over on my mod [here](https://gitlab.com/parkermc/advancement-book/issues) (since it will be work on that mod instead of the pack) and I can throw a test build your way to try.

**Comment by ParkerMc** [comment]
Do any of y'all have this issue on a server without Sponge? SpongePowered/SpongeForge#2503

**Comment by d4julian** [comment]
Yes my server has sponge installed.

**Comment by ApolloMCC** [comment]
I have sponge and the issue is easily fixed.  d4julian check what parker said

**Comment by ParkerMc** [comment]
Only fix I know if is to remove Sponge. Is that what you are talking about @ApolloMCC ?
Also in the future make sure you fill out everything on the bug report. We could have gotten to this point much faster.

**Comment by d4julian** [comment]
@ParkerMc I believe it was fixed in one of the newer Sponge versions. I'll keep you updated with results.
