### ISSUE TITLE
Duplication bug - BDS&M

### ISSUE THREAD

**Issue by jeramyreid** [Darkosto/SkyFactory4Issues#318]
## Bug Report
When using a crate with an Ore Dictionary upgrade, you can convert any type of Acorn or Resin into any other type, as long as you've been able to get one to pre-load it with.

## Expected Behaviour
When you place an acorn into the crate, you shouldn't be able to Oredict it into higher tier resources for free.

## Possible Solution
Disable Ore Dictionary upgrade in the BDS&M mod, or remove Acorns from foodAcorn, remove resin from treeResin, to prevent oredicting across different types.

## Steps to Reproduce (for bugs)
1. Place a BDS&M crate.
2. Apply an Ore Dictionary upgrade.
3. Feed one or more acorn/resin into the crate to set the output type.
4. Add all your other acorns/resins to convert them all to that type.

## World Information
* Preset: Village
* Prestige: Enabled
* Modpack Version world created in: 4.0.1
* Additional Content Installed: None, default build.

**Comment by Durandle** [comment]
why should you not be able to convert them the only challenge is getting them in the first place
non of the resin's or acorns are easier or harder to get than the others
being able to oredict them just means that the excess acorns you end up can be converted into diamond/emerald/redstone or lapis

the same could be argued about being able to oredict leaves into cottonwood leaves that can be dried into string

it is not exploitable like the old IC2 and big reactors being able to run a positive loop cycle (at least i think it was with IC2 that the interaction was it was never in a pack i played just something i read about learning how big reactors worked back in the SF2.4 days)

**Comment by Darkosto** [comment]
I'm going to alter this commit a bit. I disagree that the majority of items need to be blacklisted since this defeats the entire purpose of why this item exists in the first place. The idea that you still have to acquire the items in the first place is the real challenge. 

I'm leaving a blacklist with a number of items on it, but I am removing a few that give it purpose. For example, many leaves don't have much of a purpose outside of early game. This upgrade was designed to give items sitting in storage a use.

**Comment by Darkosto** [comment]
Having said that and looking into this a bit more, a lot of these items are not an issue because of the oredict. The uncrafting grinder is the root problem. Many of these items (like blockGlass and plankWood) should be unable to be uncrafted to get things like dyes.
