### ISSUE TITLE
resource hog type change

### ISSUE THREAD

**Issue by avidgamer5918** [Darkosto/SkyFactory4Issues#339]
## Bug Report
if you use a mob folder on a resource hog and then place it back down it changes the type of hog 

## Expected Behaviour
give back same hog

## Steps to Reproduce (for bugs)
https://clips.twitch.tv/HotGenerousMangoYouWHY

## World Information

* Preset:sky factory 4 default 

* Prestige: no

* Modpack Version world created in:4.0.1

* Additional Content Installed:ftb lib, ftb utils, content creator intigration

## Client Information

* Modpack Version:4.0.1
* Java Version:java 8 201
* Launcher Used:twitch
* Memory Allocated:7 gigs
* Server/LAN/Single Player:server
* Optifine Installed:no 
* Shaders Enabled:no

## Server Information
* Java Version:
* Operating System:linix
* Hoster/Hosting Solution:torchnode
* Sponge (Non-Vanilla Forge) Server:no

**Comment by darkhax** [comment]
@Darkosto I looked into this issue for you. The issue is that the mob folder doesn't keep the NBT of the mob, so when you spawn the pig back in it will randomize the variant. The solution for this is to make sure the resource hog is blacklisted in the Real Filing Cabinets config, and any other mods that add mob spawning mechanics. 

The class of the resource hog is `net.darkhax.resourcehogs.entity.EntityResourceHog` and the registry ID is `resourcehogs:resourcehog`. This is the info you should need to blacklist it.

**Comment by sk2048** [comment]
Mob Folders don't check the blacklist. Have submitted PR to resolve this.

bafomdad/realfilingcabinet#65
