### ISSUE TITLE
Server issue when activating then deactivating prestige mode

### ISSUE THREAD

**Issue by r3b3lxxleader** [Darkosto/SkyFactory4Issues#342]
## Bug Report
 People on server not being able to use vein miner or any prestige locked recipes.

## Steps to Reproduce (for bugs)

1. We enabled the prestige mode on our server earlier today and then disabled it but now anyone who was logged in or logged in at the time can't vein mine or access recipes and prestige has been force disabled
2. We have tried removing all there player data

## Logs

* Client/Server Log: didn't crash
* Crash Log:

## World Information

* Preset: sky factory 4

* Prestige: Server was started without it enabled but was enabled before the issue was mentioned to the person that enabled it and was disabled.
 4.0.0
* Modpack Version world created in: 4.0.0

* Additional Content Installed: Thut essentials. Thut Perms

## Client Information

* Modpack Version: 4.0.0
* Java Version: 2831
* Launcher Used: Twitch
* Memory Allocated: 6
* Server/LAN/Single Player: server 
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version: 2831
* Operating System: Windows
* Hoster/Hosting Solution: Private
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
When Prestige is disabled there is currently no way for other mods to know about this without constantly checking. Currently, when Prestige is disabled all other mods in the pack continue to behave as though it is enabled. I believe a request has been made to the mod author that will change this.

For the time being, the ideal situation is you don't change the state of prestige once starting a world. If you have to, the easiest solution is having the players logoff and deleting the player data so that when your players next join the world the world setup function can run again. Make sure they store their items in a chest!

Alternatively, if you want to reenable prestige, there is an update out for the mod that resolves the issue that caused you to disable it. If that's not something you want to deal with (and I don't blame you), there will also be an update out for SkyFactory 4 in the next few days that includes that update as well as a whole host of other fixes and we'll be recommending it to all players!

**Comment by r3b3lxxleader** [comment]
> When Prestige is disabled there is currently no way for other mods to know about this without constantly checking. Currently, when Prestige is disabled all other mods in the pack continue to behave as though it is enabled. I believe a request has been made to the mod author that will change this.
> 
> For the time being, the ideal situation is you don't change the state of prestige once starting a world. If you have to, the easiest solution is having the players logoff and deleting the player data so that when your players next join the world the world setup function can run again. Make sure they store their items in a chest!
> 
> Alternatively, if you want to reenable prestige, there is an update out for the mod that resolves the issue that caused you to disable it. If that's not something you want to deal with (and I don't blame you), there will also be an update out for SkyFactory 4 in the next few days that includes that update as well as a whole host of other fixes and we'll be recommending it to all players!

I already tried deleting player data and it didn't make a difference when he rejoined the server. It was more miscommunication that it was turned on I believe but that happens sometimes.4

**Comment by jaredlll08** [comment]
So the prestige data is stored in ~/prestige, you need to delete those files, alternatively, you could run the 
`/prestige force enabled/disabled` command which will update the data for everyone currently online.

**Comment by r3b3lxxleader** [comment]
> So the prestige data is stored in ~/prestige, you need to delete those files, alternatively, you could run the
> `/prestige force enabled/disabled` command which will update the data for everyone currently online.

for some reason we couldn't get the prestige files to delete off the console, but we were able to get a fix figured out using the /gamestage command and command blocks. Also the prestige command wouldn't do anything for the situation.
