### ISSUE TITLE
Cheaper Void Upgrade (BDS&M)

### ISSUE THREAD

**Issue by BrainInBlack** [Darkosto/SkyFactory4Issues#432]
## Context
As a server owner, i consider the void upgrade essential to the health of the server. While ender pearls are not "expensive", it takes a while until less "skilled" players are able to "waste" them on upgrades for their storage system.

All that wouldn't be that bad, if the trash can would accept items at a higher rate. It has trouble keeping up with a rather small bonsai farm connected to the very basic item ducts.

Therefore i propose to replace the void stone with just obsidian. Yes, it is way cheaper... but server owners will be happy that something essential is easily obtainable.

**Comment by LezChap** [comment]
Bonsai Hopper Pots will automatically void anything the inventory below them doesn't have space for.  While I'm not arguing against cheaper void upgrades (they could be a tad cheaper imo), in the mean time you can "advise" your players to place them on Filing Cabinets or Shipping Containers instead of pipes.

**Comment by BrainInBlack** [comment]
We have a workaround, buffering through a chest and "voiding" into several trash cans. It helps, but is not the "elegant" solution ;)

**Comment by BrainInBlack** [comment]
Was implemented in pack version 4.0.3
