### ISSUE TITLE
Cant place parabox in Compactsky world type

### ISSUE THREAD

**Issue by st0rmhawk** [Darkosto/SkyFactory4Issues#478]
## Bug Report

The parabox only seems to be able to be placed in the overworld(rejects with error saying "a temporal anomaly prevents placing this here") which means it is not possible to do parabox and generate prestige points in compactsky as it is also not possible to alter blocks in the overworld/hub.
I have tested in a few machines and in all cake dimensions except TF(needs prestige to get there).

## Expected Behaviour

If the world type allows altering hub you could add one to the hub with some form of wireless(cross dim) energy transfer or a 3x3 cube next to it and allow us to build cubes in that and use tunnels to push energy outwards.

## Steps to Reproduce (for bugs)

1. create compactsky world(with prestige)
2. attempt to place parabox

## Logs

* Client/Server Log: https://gist.github.com/st0rmhawk/4e05f5c80614e2e36a3a779f638cc06d
* Crash Log: N/A

## World Information

* Preset: Compactsky

* Prestige: yes

* Modpack Version world created in: 4.0.1/4.0.2

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version: 1.8.0.51
* Launcher Used: Twitch
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by MaxBellc** [comment]
Same issue here.

**Comment by YasenGaming245** [comment]
yup, I got it too

**Comment by Xuhybrid** [comment]
I just wasted the last 10 hours of my life getting to the Parabox and all the other stuff you have to do because Compactsky has no functional Telepastries.

This is only one of the various issues with Compactsky where the pack creator didn't consider the functionality at all, leading to me following a rabbit hole so deep only to find it doesn't work in Compactsky, again and again. This whole island type is a mistake. I wish i'd never started it.
