### ISSUE TITLE
Barrels, Drums, Storage & More - uninstall 4k upgrade gives 256k and 64k ugprades back

### ISSUE THREAD

**Issue by Dynamic1237** [Darkosto/SkyFactory4Issues#537]
## Bug Report

If you install a 4k Upgrade: Capacity x4096, then use the Uninstall Upgrades utility it gives back 3x 256k and 3x 64k upgrades.

Either allow it to give back 4k upgrade, or allow upgrades to be combined into higher tier, QoL if you spent resources on the larger upgrades to begin with

## Expected Behaviour

After installing 4k mod upgrade, removing upgrade gives back 3x 64k and 3x256k instead

Possibly have it give back 4k mod when 4k was installed, or allow mods to be combined to 4k, QoL change if you spent resources on upgrades in the first place
## Possible Solution

Possible reason is that the crate does not know the difference when max upgrades are installed and just gives back what is equivalent.

## Steps to Reproduce (for bugs)

1. Install 4096k upgrade into wooden crate
2. Remove with Uninstall Upgrade

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkiiiIslands

* Prestige: yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version: Version 8 Update 201
* Launcher Used: Twitch
* Memory Allocated: 9216MB
* Server/LAN/Single Player: Server (able to reproduce on new singleplayer world created in 4.0.2)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Funwayguy** [comment]
So let me get this straight. You threw in an upgrade 4x the max capacity of the crate (which is shown before you apply it) and you were unhappy that it didn't refund you the wasted portion?

"But why allow someone to do that in the first place?"

Because in testing it was a pain to have to break down upgrades to fit exactly. It was decided to just let players accept a minor loss in return for the convenience of less uncrafting and clicking if they chose to. Now _usually_ people would only throw in something like 1K and take a mere 64 capacity loss. 4K should really only ever be necessary on a metal crate.

**Comment by Dynamic1237** [comment]
Thank you for your response Funwayguy, was just reporting the issue, did not know it was known. It is a great mod, thank you for creating it.
