### ISSUE TITLE
Pacifist Mode - No way to create Glitch Infused Armor (Deep Mob Learning)

### ISSUE THREAD

**Issue by Gobus** [Darkosto/SkyFactory4Issues#614]
There currently isn't any crafting recipe for Glitch Infused Hearts or Unstable Glitch Fragments that you could use in Pacifist Mode, therefore it's impossible to obtain without doing the Trials.

**Comment by LezChap** [comment]
If mobs die to spikes, does it fail Pacifist Mode?

**Comment by Gobus** [comment]
You'd have to kill them to get the Key anyway, and I don't think anything other than killing them yourself attunes them.

**Comment by Revv1e** [comment]
bump
I really feel like there should be some sort of way to match these sort of killing drops to the pacifist route, make them exceptions cuz its all like simulation? Or maybe just have the glitches drop from pristine matter from specific mobs? I think the achievements need to, rather than just be reused, actually remade to match pacifism, cuz as far as I know the twilight forest ones cant be completed because it requires killing.

**Comment by Gobus** [comment]
Yeah exactly, that's why I kinda stopped playing the pacifist save, because some achievements weren't even possible to do because they do require killing.
