### ISSUE TITLE
Why is AE2 stripped down?

### ISSUE THREAD

**Issue by nightshard** [Darkosto/SkyFactory4Issues#638]
You've taken the fun out of AE2.

I get it that you're trying to use only some elements from some mods in order to push some less known mods forward, but with that said.

You've disabled AE2 channels and don't have AE2 Stuff, which makes it no fun, not fun whatsoever.

**Comment by Streamcyper** [comment]
AE2 Stuffs was originally going to be in the pack but due to a bug it had to be removed. https://clips.twitch.tv/PiliablePrettiestWoodcockBloodTrail

And I most likely channels were disabled because it makes it more accessible to more people, as Sky Factory 4 was not meant to be a hard pack. If you want to add channels back into AE2 you can do that in the config /config/AppliedEnergistics2/AppliedEnergistics2.cfg  -  `networkfeatures { B:Channels=false }` and change that to true. Tho you might need to do some tweaking to get the recipe for controller to work unless you want to creative those in.
