### ISSUE TITLE
Game Crash when i click on Play on Launcher

### ISSUE THREAD

**Issue by Undravel** [Darkosto/SkyFactory4Issues#718]
## Bug Report

When i click on the Play Button after launch the mod Pack on Twitch,
The Minecraft Launcher tell me that there is "an unexcepted issue occurred".

## Expected Behaviour

The pack launches.

## Steps to Reproduce (for bugs)

1. Download the mod pack (Any versions)
2. Launche the game

## Logs

* Client/Server Log:
* Crash Log: https://github.com/Undravel/SkyFact4Crash/blob/master/latest.txt

## Client Information

* Modpack Version: Any versions
* Java Version: Java 8 Update 141 (build 1.8.0_141-b15)
* Launcher Used: Twitch
* Memory Allocated: 6144
* Server/LAN/Single Player: none
* Optifine Installed: none
* Shaders Enabled: none

**Comment by zimmemon** [comment]
I am having the same problem with launching my game 

don't know I am allowed but here is the crash log if I am nor allowed to put crash logs like this let me know :)


Unable to launch java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/ai/attributes/AbstractAttributeMap at java.lang.Class.getDeclaredConstructors0(Native Method) at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) at java.lang.Class.getConstructor0(Class.java:3075) at java.lang.Class.getConstructor(Class.java:1825) at net.minecraft.entity.EntityList.func_191303_a(EntityList.java:410) at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:280) at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:505) at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) at net.minecraft.client.main.Main.main(SourceFile:123) ... 6 more Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.ai.attributes.AbstractAttributeMap at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 15 more Caused by: java.lang.ClassFormatError: Duplicate field name&signature in class file net/minecraft/entity/ai/attributes/AbstractAttributeMap at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:760) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ... 17 more

**Comment by justinrusso** [comment]
Check out the discord for help http://bit.ly/DarkostoDiscord
