### ISSUE TITLE
Crafting recipies

### ISSUE THREAD

**Issue by DasHeinzchen** [Darkosto/SkyFactory4Issues#882]
I downloaded the pack from the technic launcher and copied the mods, the configs and the scripts into my .minecraft folder.

Now the problem: I can't craft any saplings and I can't do anything with the items of the sky orchards mod.

I hope someone can help me.

**Comment by sk2048** [comment]
Whatever is on the Technic launcher has nothing to do with us. Get the mod pack through either the Twitch launcher or ATLauncher, or via the CurseForge client download using something like MultiMC.

Additionally, this is not an issue with the pack, for support of this nature please use the appropriate channel on Discord: https://discord.gg/darkosto

**Comment by DasHeinzchen** [comment]
Sorry i mean twitch not Technic launcher

**Comment by ktole1999** [comment]
you need to copy the scripts folder as well

**Comment by ktole1999** [comment]
if you installed it from technic then it should run from the technic launcher. you can also download using the twitch launcher.

**Comment by acoskuner500** [comment]
Same thing just happened to me, and this was especially annoying because it happened right before I could get my first prestige point, I only had slime and bacon saplings left to do. @sk2048 please is there anything you know or could do to help?

If it matters, there was no crash report so I don't think I can file an issue (formally at least).
