### ISSUE TITLE
Flux networks wont pull energy from induction matrix

### ISSUE THREAD

**Issue by GGOATR** [Darkosto/SkyFactory4Issues#896]
## Bug Report
I have 2 network.1 for input to matrix other one to output.Flux point for input works compeletely fine but flux plug for output wont pull the energy
## Steps to Reproduce (for bugs)

1.https://prnt.sc/nmj0jn

2.https://prnt.sc/nmj0tf

3.https://prnt.sc/nmj0yw

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in: 4.0.5

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by LezChap** [comment]
I have an idea on what the issue may be, but I need a little more information...what all plugs do you have on the purple network, and how are they configured, and what tile entities are they attempting to power...if they're powering cables/pipes/fluxducts/etc, what are those trying to power?

**Comment by GGOATR** [comment]
Purple flux points powers mekanism machines nuclearcraft machines and some industrial foregoing machines.And points attached to fluxducts

**Comment by LezChap** [comment]
I've heard reports that Points can't directly power most Mekanism machines, but if you're using a Fluxduct, that shouldn't be an issue.  You wouldn't happen to have a Matter Overdrive Molecular Inscriber on one of those Fluxducts, would you?

**Comment by GGOATR** [comment]
I had one but i removed it it still doesnt work

**Comment by LezChap** [comment]
The fluxducts can remain in a bugged state even after you remove the Inscriber.  Try breaking and replacing all the ones that were connected to the inscriber, and let us know if that fixes the problem or not.

**Comment by GGOATR** [comment]
I did it but it didnt solve my problem

**Comment by LezChap** [comment]
It may have corrupted your Flux Networks data and tile entities as well...unfortunately you can't reset them as easily as Fluxducts...if you can cheat in in new components to replace all the old Flux Points/Plugs/Controllers in your world, try that...and make sure you delete your network (in the network list in the GUI), break them all, and void the old ones before you start making a new network and replacing the parts, just to be sure you don't spread the corrupt data around if you try to do it piecemeal.  (making sure to void all old stuff first may not be necessary...but it's probably easier to be thorough the first time over having to do it twice.)

If THAT doesn't work, you're probably going to have to remove and delete/void all old Flux Networks items, close your world, and go into your save folder and delete the data files manually.  Be sure you backup your world before you do these modifications, as they have the possibility to create other problems or even world crashes/corruptions, and I want to make sure you can return to an otherwise playable world.  The data files are located in your "/saves/WORLDNAME/data/" folder and delete all "sonar" files.  (This will remove all networks and I think it'll also impact any Practical Logistics things you've set up...and I'm not sure how it'll impact Practical Logistics as I didn't have anything from that set up when I did my testing...it could create a error that crashes your world when you try to load it, so as I said before...BACKUPS!)

When I broke flux networks with this bug in a test world, deleting the files as I mentioned in the second paragraph worked to make Flux Networks work again, but I wasn't concerned about possibly corrupting the world or data loss, so I'd try the in-game solution first in a world I actually care about.

**Comment by GGOATR** [comment]
I switched the shape of induction matrix and it solve my prolem thx for your help
