### ISSUE TITLE
Party Pickaxe deletes visual but not physical block.

### ISSUE THREAD

**Issue by Cypherdud** [Darkosto/SkyFactory4Issues#902]
## Bug Report
destroying a block with the party pickaxe will kill the animation, but when you try to walk where it was you cant move through it and get stuck. placing a block on that invisible space will reveal the hidden block and you can then destroy it with a normal pick/ paxel.

## Expected Behaviour
the block dissapears from visual instead of being turned into an entity

## Possible Solution
place a block on the spot where it was to reveal it and destroy is with something else

## Steps to Reproduce (for bugs)

1. https://youtu.be/cY6M4YP-Xso
2.

## Logs

 

* Client/Server Log: https://gist.github.com/Cypherdud/c019c5f9cf7b971cf029a578a420c923
* Crash Log:

## World Information

* Preset: blazing pyrotheum floor

* Prestige: no

* Modpack Version world created in: v4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version: v4.0.5
* Java Version: 1.12.2
* Launcher Used: 2.1.2674
* Memory Allocated: 6400mb
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by LezChap** [comment]
This sounds like a desync that's common in MC.  Is it every block you try to break, every time...or does it happen randomly when you're mining out blocks?

**Comment by Cypherdud** [comment]
> This sounds like a desync that's common in MC. Is it every block you try to break, every time...or does it happen randomly when you're mining out blocks?

Look at the video

**Comment by LezChap** [comment]
Yep, watched the video, that looks like a pretty bad section of desync, but otherwise the behavior is exactly like every other desync I've experienced in MC for the last 10 years or so...the video shows you were able to break blocks with the Party Pickaxe without an issue multiple times.

What's going on is you attempt to break the box, and the client/rendering engine believes the blocks are broken, but the underlying "server" (yes, even Single Player has a "server" in this context) that manages the world says "no, that's not actually broken" (usually because it broke too fast and the server didn't get a chance to register it), and you end up bouncing off invisible blocks.  The only solution is to attempt to place a block where the invisible block is, like you showed in your video, close and re-open the world (or log out/in on a server)...or you could attempt to reload chunks with the F3+A combo, but that's not been reported to work in all cases.
