### ISSUE TITLE
Server Hangs and the Crashes when attempting to sync baseline info from Astral Sorcery

### ISSUE THREAD

**Issue by May-Jor** [Darkosto/SkyFactory4Issues#904]
## Bug Report

Server Crash on: [Astral Sorcery] Synchronizing baseline information to
## Expected Behaviour

The server to sync baseline info of player
## Steps to Reproduce (for bugs)

1. Attempt to connect
2. Server Crash

## Logs

* Client/Server Log:
[latest.log](https://github.com/Darkosto/SkyFactory4Issues/files/3165062/latest.log)

* Crash Log:
[crash-2019-05-10_00.40.44-server.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3165063/crash-2019-05-10_00.40.44-server.txt)

## World Information

* Preset: DEFAULT

* Prestige: DISABLED

* Modpack Version world created in: 4.0.5

* Additional Content Installed: N\A

## Client Information

* Modpack Version: 4.0.5
* Java Version: 1.8.0_144
* Launcher Used: Twitch
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: N\A
* Shaders Enabled: N\A

## Server Information
* Java Version: 1.8.0_144
* Operating System: Windows 10
* Hoster/Hosting Solution: Self
* Sponge (Non-Vanilla Forge) Server: N\A

**Comment by sk2048** [comment]
This issue appears unrelated to Astral. Your server is getting stuck calculating what should happen to item entities near where you are spawning in. You likely have an extreme number of items spilt into the world in a very confined space, and the server can't calculate what should happen to all the overlapping entities in a reasonable time.

If you are familiar with MCEdit or an NBT editing program, you can use those to remove entities from around where you're spawning.

Otherwise, you could try changing `max-tick-time` in server.properties to `-1` (infinite) and entering the command `/kill @e[type=item]` into the server console. You won't see an output immediately, but when the server completes the tick (could be several minutes) you should see a lot of messages about items being killed.

**Comment by May-Jor** [comment]
Turns out it was a mass of Cobblestone that was being dropped from an incomplete power setup. Fixed, and thanks to @sk2048 for the help!
